### PR TITLE
feat: review title vs rating

### PR DESCRIPTION
**Pull request by what-a-life**

### CODE REVIEW

**Review by B4rtSL — CHANGES_REQUESTED** [review]
Change Heading size in markdown to '##'

**Comment by what-a-life** [comment]
> Change Heading size in markdown to '##'

Done

**Review by B4rtSL — APPROVED** [review]
Good job :)

**Review by BartekCzarnowski — APPROVED** [review]

**Review by BartekCzarnowski — APPROVED** [review]
wszystko git

**Pull request merged**
